namespace WarcraftSim.Core.Simulation.Engine;

public sealed class DamageTakenResourceGenerationDefinition
{
    public string Key { get; init; } = "";

    public string Name { get; init; } = "";

    public string ResourceKey { get; init; } = "";

    // Stable reference-health divisor used by the ruleset-specific resource
    // formula. Keeping this separate from the actor's own maximum health is
    // important for normalized systems whose generation must not change when
    // the player equips more Stamina.
    public decimal ReferenceHealth { get; init; }

    // Amount of resource granted when eligible damage, after any configured
    // replacement mitigation, equals ReferenceHealth.
    public decimal ResourcePerReferenceHealthOfEligibleDamage { get; init; }

    public bool IgnoreArmorMitigation { get; init; }

    // When actual Armor is ignored, a ruleset can replace it with a stable
    // expected reduction instead of treating the hit as completely unarmored.
    // This is only applied to events whose mitigation type is Armor.
    public decimal IgnoredArmorReplacementReductionPercent { get; init; }

    public bool IgnoreAbsorbs { get; init; }

    // Blocking remains a real reduction even when a ruleset replaces actual
    // Armor for resource-generation purposes.
    public bool BlockReducesEligibleDamage { get; init; } = true;

    // Classic-style damage-taken Rage is generated by damage from an
    // external attacker, not self-inflicted/resource-conversion damage.
    public bool RequiresExternalSourceActor { get; init; } = true;
}
