namespace WarcraftSim.Core.Simulation.Engine;

public sealed class DamageTakenResourceGenerationDefinition
{
    public string Key { get; init; } = "";

    public string Name { get; init; } = "";

    public string ResourceKey { get; init; } = "";

    // Amount of resource granted when eligible incoming damage equals
    // 100% of the target's maximum health.
    public decimal ResourcePerMaximumHealthOfEligibleDamage { get; init; }

    public bool IgnoreArmorMitigation { get; init; }

    public bool IgnoreAbsorbs { get; init; }

    // Blocking remains a real reduction even when a ruleset ignores Armor
    // for resource-generation purposes.
    public bool BlockReducesEligibleDamage { get; init; } = true;

    // Classic-style damage-taken Rage is generated by damage from an
    // external attacker, not self-inflicted/resource-conversion damage.
    public bool RequiresExternalSourceActor { get; init; } = true;
}
